FILE_NAME_GREETINGS = 'greetings.txt'

DEFAULT_GREETING_FIRST = 'Hello'
DEFAULT_GREETING_SECOND = 'World'

GREETING_SECOND = '🌍'
GREETING_PUNCTUATION = '!'
SEP =  ' '

EMOJI_ENCODINGS = ('UTF-8', 'UTF-16', 'UTF-32')