FILE_NAME_GREETINGS = 'greetings.txt'
FILE_AUDIO_EXTENSION = 'wav'

DEFAULT_GREETING_FIRST = 'Hello'
DEFAULT_GREETING_SECOND = 'World'
SEP =  ' '

GREETING = DEFAULT_GREETING_FIRST  + SEP + DEFAULT_GREETING_SECOND

WORLD_EMOJI = '🌍'
GREETING_PUNCTUATION = '!'


EMOJI_ENCODINGS = ('UTF-8', 'UTF-16', 'UTF-32')

ENCODING = 'UTF-8'

PREFIX_TRACE_ID =  'HelloWorld'

TIMEOUT_SECONDS = 10 #for calling translator resource

DEFAULT_VOICE = 'en-US-JennyNeural'
DIRECTORY_AUDIO ='audio'
